name: CI/CD Pipeline

on:
  workflow_dispatch: {}

  push:
    branches: [ main ]
    paths:
      - "templates/**"
      - "main.go"
      - "Dockerfile"
      - "k3s/deployment.yaml"
      - "k3s/service.yaml"
      - "k3s/namespace.yaml"

  pull_request:
    branches: [ main ]
    paths:
      - "templates/**"
      - "main.go"
      - "Dockerfile"
      - "k3s/deployment.yaml"
      - "k3s/service.yaml"
      - "k3s/namespace.yaml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Obter código-fonte
        uses: actions/checkout@v4

      - name: Fazer Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir e enviar imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/pip:v${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Obter código-fonte
        uses: actions/checkout@v4

      - name: Configurar acesso ao cluster K3S
        uses: azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Realizar deploy no Kubernetes (K3S)
        uses: azure/k8s-deploy@v5
        with:
          namespace: pip
          manifests: |
            k3s/deployment.yaml
            k3s/service.yaml
            k3s/namespace.yaml
          images: |
            ghcr.io/${{ github.repository_owner }}/pip:v${{ github.run_number }}
          
          pull-images: true
          strategy: basic
          route-method: service
          version-switch-buffer: 0
          traffic-split-method: pod
          percentage: 0
          action: deploy
          force: false
          annotate-resources: true
          annotate-namespace: true
